/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.trinet.model.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Profile service. Represents a row in the &quot;userprofile_Profile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.trinet.model.model.impl.ProfileModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.trinet.model.model.impl.ProfileImpl}.
 * </p>
 *
 * @author ronak.parekh
 * @see Profile
 * @see com.trinet.model.model.impl.ProfileImpl
 * @see com.trinet.model.model.impl.ProfileModelImpl
 * @generated
 */
public interface ProfileModel extends BaseModel<Profile> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a profile model instance should use the {@link Profile} interface instead.
	 */

	/**
	 * Returns the primary key of this profile.
	 *
	 * @return the primary key of this profile
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this profile.
	 *
	 * @param primaryKey the primary key of this profile
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the ID of this profile.
	 *
	 * @return the ID of this profile
	 */
	public long getId();

	/**
	 * Sets the ID of this profile.
	 *
	 * @param id the ID of this profile
	 */
	public void setId(long id);

	/**
	 * Returns the email of this profile.
	 *
	 * @return the email of this profile
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this profile.
	 *
	 * @param email the email of this profile
	 */
	public void setEmail(String email);

	/**
	 * Returns the user ID of this profile.
	 *
	 * @return the user ID of this profile
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this profile.
	 *
	 * @param userId the user ID of this profile
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this profile.
	 *
	 * @return the user uuid of this profile
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this profile.
	 *
	 * @param userUuid the user uuid of this profile
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the associate ID of this profile.
	 *
	 * @return the associate ID of this profile
	 */
	public long getAssociateId();

	/**
	 * Sets the associate ID of this profile.
	 *
	 * @param associateId the associate ID of this profile
	 */
	public void setAssociateId(long associateId);

	/**
	 * Returns the first name of this profile.
	 *
	 * @return the first name of this profile
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this profile.
	 *
	 * @param firstName the first name of this profile
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this profile.
	 *
	 * @return the last name of this profile
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this profile.
	 *
	 * @param lastName the last name of this profile
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the summary of this profile.
	 *
	 * @return the summary of this profile
	 */
	@AutoEscape
	public String getSummary();

	/**
	 * Sets the summary of this profile.
	 *
	 * @param summary the summary of this profile
	 */
	public void setSummary(String summary);

	/**
	 * Returns the year of experience of this profile.
	 *
	 * @return the year of experience of this profile
	 */
	public int getYearOfExperience();

	/**
	 * Sets the year of experience of this profile.
	 *
	 * @param yearOfExperience the year of experience of this profile
	 */
	public void setYearOfExperience(int yearOfExperience);

	/**
	 * Returns the experience of this profile.
	 *
	 * @return the experience of this profile
	 */
	@AutoEscape
	public String getExperience();

	/**
	 * Sets the experience of this profile.
	 *
	 * @param experience the experience of this profile
	 */
	public void setExperience(String experience);

	/**
	 * Returns the primary skills of this profile.
	 *
	 * @return the primary skills of this profile
	 */
	@AutoEscape
	public String getPrimarySkills();

	/**
	 * Sets the primary skills of this profile.
	 *
	 * @param primarySkills the primary skills of this profile
	 */
	public void setPrimarySkills(String primarySkills);

	/**
	 * Returns the secondary skills of this profile.
	 *
	 * @return the secondary skills of this profile
	 */
	@AutoEscape
	public String getSecondarySkills();

	/**
	 * Sets the secondary skills of this profile.
	 *
	 * @param secondarySkills the secondary skills of this profile
	 */
	public void setSecondarySkills(String secondarySkills);

	/**
	 * Returns the client name of this profile.
	 *
	 * @return the client name of this profile
	 */
	@AutoEscape
	public String getClientName();

	/**
	 * Sets the client name of this profile.
	 *
	 * @param clientName the client name of this profile
	 */
	public void setClientName(String clientName);

	/**
	 * Returns the education of this profile.
	 *
	 * @return the education of this profile
	 */
	@AutoEscape
	public String getEducation();

	/**
	 * Sets the education of this profile.
	 *
	 * @param education the education of this profile
	 */
	public void setEducation(String education);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Profile profile);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Profile> toCacheModel();

	@Override
	public Profile toEscapedModel();

	@Override
	public Profile toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}